### ISSUE TITLE
Feat : 오늘의 딜

### ISSUE THREAD

**Issue by hyejee0504** [Team5-FE/clone-ohou#3]
## 작업 개요
오늘의 딜 세션을 모바일, 테블릿, 웹페이지에 맞도록 반응형으로 작업하였고 최대한 비슷한 부분을 찾아 컴포넌트 작업함.

## Todo
- [x] 오늘의 딜 마크업 작업
- [x] 오늘의 딜 컴포넌트 작업
- [x] 오늘의 딜 레이아웃 작업
- [x] ✏
