### ISSUE TITLE
Feat : 오늘의 인기사진

### ISSUE THREAD

**Issue by hyejee0504** [Team5-FE/clone-ohou#4]
## 작업 개요
오늘의 인기 사진을 모바일, 테블릿, 웹페이지에 맞도록 반응형으로 작업하였고 최대한 비슷한 부분을 찾아 컴포넌트 작업함.

## Todo

- [x] 오늘의 인기 사진 마크업 작업✏
- [x]  오늘의 인기 사진 컴포넌트 작업
- [x] 오늘의 인기 사진 스타일 작업
