### ISSUE TITLE
Feat : 오늘의 스토리 영역

### ISSUE THREAD

**Issue by annasyun** [Team5-FE/clone-ohou#7]
## 작업 개요
오늘의 스토리 영역 작업
## Todo

- [x] 오늘의 스토리 마크업✏
- [x] 오늘의 스토리 CSS✏
- [x] 카테고리별 상품 찾기 마크업✏
- [x] 카테고리별 상품 찾기 CSS✏
